### ISSUE TITLE
Pls no hack

### ISSUE THREAD

**Issue by devkarthin** [acepj60/aduh4#1]
Hi, you hack my website karthin.com. Pls remove hack. If it was for somethig i di d, im sorry.

**Comment by acepj60** [comment]
Oke 😊👍

Pada tanggal Min, 26 Feb 2023 08.46, Karthin Srinavakili <
***@***.***> menulis:

**Comment by devkarthin** [comment]
I have now removed the GitHub Pages DNS records. Thank you, especially for not doing anything malicious.
